version: "3.5"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3030:3030"
    stdin_open: true
    tty: true
  mysql:
    image: mysql:8.0
    # image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flow
      MYSQL_USER: flow
      MYSQL_PASSWORD: flow
